name: Crypto News Poster
on:
  schedule:
    - cron: '0 9 * * *'  # 9 AM UTC
    - cron: '0 18 * * *' # 6 PM UTC
jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser tweepy
      - name: Run script for client1
        env:
          CLIENT1_CONSUMER_KEY: ${{ secrets.CLIENT1_CONSUMER_KEY }}
          CLIENT1_CONSUMER_SECRET: ${{ secrets.CLIENT1_CONSUMER_SECRET }}
          CLIENT1_ACCESS_TOKEN: ${{ secrets.CLIENT1_ACCESS_TOKEN }}
          CLIENT1_ACCESS_TOKEN_SECRET: ${{ secrets.CLIENT1_ACCESS_TOKEN_SECRET }}
        run: python app.py client1