name: Run script for client1
  env:
    CLIENT1_CONSUMER_KEY: ${{ secrets.CLIENT1_CONSUMER_KEY }}
    CLIENT1_CONSUMER_SECRET: ${{ secrets.CLIENT1_CONSUMER_SECRET }}
    CLIENT1_ACCESS_TOKEN: ${{ secrets.CLIENT1_ACCESS_TOKEN }}
    CLIENT1_ACCESS_TOKEN_SECRET: ${{ secrets.CLIENT1_ACCESS_TOKEN_SECRET }}
  run: python app.py client1